### ISSUE TITLE
[FR] Subcommands

### ISSUE THREAD

**Issue by UnEnanoMas** [Rushil13579/AdminTrollV2#3]
It would be nice to add the option that all the commands were in 1 only.

For example:

/at help: Show the list of all commands

/at alone (player)

/at badapple (player)

That the /at or /admintrollv2 had those subcommands, so there are not so many pages when using /help

**Comment by Rushil13579** [comment]
But that would add an extra argument you have to type every time you want to do a troll. I was going to do that at first, but then dint do it for this very reason, also that most really good troll plugins like TrollBoss and TrollCommands++ have it separate like that. 
Also, who even uses /help lol.

**Comment by UnEnanoMas** [comment]
Well, for me it is a bit annoying to have all the commands separately, (to my liking) it would be more beautiful and orderly to have them all together with the / at

**Comment by Rushil13579** [comment]
Very well, i will take this into consideration and see what others say. Thanks for your opinion :)

**Comment by UnEnanoMas** [comment]
Finally u did it
